"use client"; // Add this line to indicate the file is a client component

import { Inter } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";

export default function RootLayout({ children }) {
  useEffect(() => {
    // Add 'dark' class to the HTML element to enable dark mode by default
    document.documentElement.classList.add("dark");
  }, []);

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

// import { Inter } from "next/font/google";
// import "./globals.css";
//
// const inter = Inter({ subsets: ["latin"] });
//
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
//
//
// "use_client";
// import "./global.css"; // Ensure this path matches your file structure
// import { useEffect } from "react";
//
// export default function RootLayout({ children }) {
//   useEffect(() => {
//     // Add 'dark' class to the HTML element to enable dark mode by default
//     document.documentElement.classList.add("dark");
//   }, []);
//
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   );
// }
