name: Daily Increment

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  call-endpoint:
    runs-on: ubuntu-latest

    steps:
      - name: Make HTTP request
        run: |
          response=$(curl -s -o response.txt -w "%{http_code}" -X POST "https://ohno-server.fly.dev/increment" \
            -H "Content-Type: application/json")
          cat response.txt
          if [ "$response" -ne 200 ]; then
            echo "Request failed with status code $response"
            exit 1
          fi
